import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({subsets: ["latin"]});
import Script from "next/script";
import React, {useRef, useEffect} from "react";

export default function Home() {
    const containerRef = useRef(null);
    useEffect(() => {
        Array.from(document.getElementsByTagName("iframe")).forEach((iframe) => {
            iframe.contentWindow.addEventListener(
                "load",
                () => {
                    const doc = iframe.contentWindow.document;
                    iframe.height = doc.body.scrollHeight;
                },
                true
            );
            iframe.contentWindow.addEventListener(
                "resize",
                () => {
                    iframe.height = iframe.contentWindow.document.body.scrollHeight + 40;
                },
                true
            );
        });
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div ref={containerRef} id='script-container'>
                    <Script type='text/javascript' src='https://test.ams4you.net/webinqcode-12356-1089.html' strategy='beforeInteractive' defer={false}>{`console.log('Hello world!');`}</Script>
                </div>
            </main>
        </>
    );
}
